# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filmes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.TextField(max_length=4, validators=[filmes.models.validators_date])),
                ('youtube', models.TextField()),
                ('capa', models.ImageField(upload_to=filmes.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='tags',
            field=models.ManyToManyField(to='filmes.Tag'),
        ),
        migrations.AddField(
            model_name='filme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
