# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='ano',
            new_name='ano_lancamento',
        ),
    ]
