# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_auto_20161029_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='youtube',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
