# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='tags',
            field=models.ManyToManyField(to='filmes.Tag'),
        ),
    ]
