# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import filmes.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_auto_20161105_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='ano_lancamento',
            field=models.TextField(max_length=4, validators=[filmes.models.validators_date]),
        ),
    ]
