# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_auto_20161112_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.FileField(upload_to='filmes/%Y/%m/%d'),
        ),
    ]
